version: "3.9"

services:
  db:
    image: postgres:17
    healthcheck:
           test: ["CMD-SHELL", "pg_isready -U postgres"]
           interval: 5s
           timeout: 5s
           retries: 5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  db_data:
